name: Construir y Publicar Imagen Docker

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Comprueba el c贸digo del repositorio
      - name: Checkout del c贸digo
        uses: actions/checkout@v4

      # Inicia sesi贸n en el Registro de Contenedores de GitHub
      - name: Iniciar sesi贸n en GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Construye la imagen Docker
      - name: Construir la imagen Docker
        run: docker build -t ghcr.io/${{ github.repository_owner }}/github-package:v1 .

      # Publica la imagen Docker en GitHub Packages
      - name: Publicar la imagen Docker
        run: docker push ghcr.io/${{ github.repository_owner }}/github-package:v1